### ISSUE TITLE
bug: Better logic for fullupdate

### ISSUE THREAD

**Issue by Rushaway** [srcdslab/sm-plugin-ThirdPerson#2]
If you get infected/killed when you are using !tp/mirror , the plugin turn it off for you. It also fullupdate the client, wich make the plugin go crazy and do random actions, like slay, move to spec etc. 
Need to investigate.

**Comment by maxime1907** [comment]
yes because if you stay in !tp and you die, the camera will be fucked

**Comment by maxime1907** [comment]
check if its still the case now with !tp then !slay @me

**Comment by Rushaway** [comment]
Hum yeah. still having this issue.
